# Generated by Django 5.1 on 2024-11-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='card_link',
            field=models.URLField(),
        ),
    ]
